### PR TITLE
ninja: fix for `generator_flags.output_dir`

### PR DESCRIPTION
**Pull request by indutny**
Put sanity back into `ninja`'s directory structures, many of them were
confusing and the names differ through the file.

Fix: #24 

cc @pmed @springmeyer

### CODE REVIEW

**Comment by springmeyer** [comment]
Thank you! Tested and it works, with both normal `ninja` binary and ninja.js.

**Comment by indutny** [comment]
Alright, landing!

**Comment by indutny** [comment]
Landed in c617f5e, and released in 1.4.11

**Comment by indutny** [comment]
Thank you for testing!

**Pull request closed without merging**
