### PR TITLE
build: convenience and coverage

### PR DESCRIPTION
**Pull request by jbergstroem**
Improve quality of life for us Unix beards and add Istanbul to get a hint of the code coverage.

### CODE REVIEW

**Comment by jbergstroem** [comment]
I chose 500msec as "slow"; my computer and travis seemed to perform around 200-400ms.

**Comment by indutny** [comment]
Thanks! This looks terrific!

The one nit that I see is that it doesn't really work well with the child processes that we spawn in tests. It seems that the coverage stats are not collected for them. Is there any way to work it around?

**Comment by jbergstroem** [comment]
Hm - missed that. I'll have a look.

**Comment by jbergstroem** [comment]
Would checking if we're running from Istanbul and modifying the child process cmd be an awful solution to you?

**Comment by indutny** [comment]
@jbergstroem this may work. I can't tell for sure until I'll see it.

**Comment by indutny** [comment]
😉

**Comment by jbergstroem** [comment]
Cool, I'll put it together tomorrow.

**Comment by jbergstroem** [comment]
"tomorrow". Sorry. I had a quick look and the result is that I don't have a quick solution. I'll see what I can do when I have some spare time.

**Comment by indutny** [comment]
@jbergstroem no worries, thank you!

**Comment by jbergstroem** [comment]
Looks like you landed parts of this? Still have Istanbul/gyp stuff on my todo.

**Comment by indutny** [comment]
@jbergstroem which parts would you suggest to land? Thanks for looking into it!

**Comment by jbergstroem** [comment]
@indutny looks like the [commits already landed](https://github.com/indutny/gyp.js/commits/master)?

**Comment by indutny** [comment]
Huuh? I didn't intend to.

**Comment by indutny** [comment]
Ok, guess we'll keep it now. 😉

**Comment by indutny** [comment]
Thank you

**Pull request closed without merging**
